### ISSUE TITLE
Failed Release build - ifdef missing

### ISSUE THREAD

**Issue by oomek** [oomek/attractplus#359]
Regression caused by https://github.com/oomek/attractplus/commit/c099387828be0710525e24ea1a7333518b314dcc

https://github.com/oomek/attractplus/blob/c099387828be0710525e24ea1a7333518b314dcc/src/fe_window.cpp#L361

```
  src/fe_window.cpp: In member function ‘void FeWindow::initial_create()’:
  src/fe_window.cpp:366:45: error: ‘SM_XVIRTUALSCREEN’ was not declared in this scope
    366 |                         { GetSystemMetrics( SM_XVIRTUALSCREEN ), GetSystemMetrics( SM_YVIRTUALSCREEN ) },
        |                                             ^~~~~~~~~~~~~~~~~
  src/fe_window.cpp:366:27: error: ‘GetSystemMetrics’ was not declared in this scope
    366 |                         { GetSystemMetrics( SM_XVIRTUALSCREEN ), GetSystemMetrics( SM_YVIRTUALSCREEN ) },
        |                           ^~~~~~~~~~~~~~~~
  src/fe_window.cpp:366:84: error: ‘SM_YVIRTUALSCREEN’ was not declared in this scope
    366 |                         { GetSystemMetrics( SM_XVIRTUALSCREEN ), GetSystemMetrics( SM_YVIRTUALSCREEN ) },
        |                                                                                    ^~~~~~~~~~~~~~~~~
  src/fe_window.cpp:367:45: error: ‘SM_CXVIRTUALSCREEN’ was not declared in this scope
    367 |                         { GetSystemMetrics( SM_CXVIRTUALSCREEN ), GetSystemMetrics( SM_CYVIRTUALSCREEN ) }
        |                                             ^~~~~~~~~~~~~~~~~~
  src/fe_window.cpp:367:85: error: ‘SM_CYVIRTUALSCREEN’ was not declared in this scope
    367 |                         { GetSystemMetrics( SM_CXVIRTUALSCREEN ), GetSystemMetrics( SM_CYVIRTUALSCREEN ) }
        |                                                                                     ^~~~~~~~~~~~~~~~~~
```
There was a `#ifdef SFML_SYSTEM_WINDOWS` there that prevented linux builds from accessing windows api specific consts.
It builds fine on branches and master. No idea why it only failed on Release build when I pushed a tag.
